version: 0.2

phases:
  install:
    commands:
      - npm i
  test:
    commands:
      - npm test
  build:
    commands:
      - npm run build
artifacts:
  files:
    - dist/**/*
    - node_modules
    - package-lock.json
    - package.json
    - ./*
